### ISSUE TITLE
[meta] Annotations 2.0 (ng)

### ISSUE THREAD

**Issue by Majkl578** [doctrine/annotations#232]
# Annotations 2.0 (ng)

This is a meta issue to track Annotations 2.0 milestones/features and aims. It's also a follow-up of #75 which collected some dust over time.

## Backward Compatibility

One of the main goals of the 2.0 version is on minimizing breakages of existing annotations and syntax compatibility with Annotations 1.x. Therefore, when talking about custom annotations and docblocks, _most_ of the user-land stuff should work without any significant effort or none at all. However most of the internal stuff is expected to be changed.

## Namespace change

- [x] The namespace will be changed from `Doctrine\Common\Annotations` to `Doctrine\Annotations`. [#193]

## Dropped features

Some features will be dropped:
- [x] `SimpleAnnotationReader` - _support for so-called unqualified references without `use`s are dropped_ [#199]
- [x] `AnnotationRegistry` - _no more annoying autoloader stuff, annotations are now autoloaded implicitly_ [#205]
- [x] `FileCacheReader` - _dropped in favor of CachedReader (based on doctrine/cache)_ [#202]
- [x] `Doctrine\Common\Annotations\Annotation` - _behavior of this class is redundant with `@Annotation` and `__get()`/`__set()` safety is ouf of scope of this library_ [#246]
- [x] `CachedReader` - _caching is to be done by consumers when needed_ [#249]
- [ ] `DocLexer`, `DocParser` and `doctrine/lexer` dependency - _these will be replaced by new AST-based parser_
---

## New parser

Initial work is split into three different stages and will come as a *new code* without refactoring existing stuff:
1. [ ] Parser - _this is the docblock parser_
   - [ ] PP language - _Doctrine Annotations syntax definition_
   - [ ] Compiler - _docblock to AST converter_
   - [ ] AST structure - _rich domain-specicic AST_
   - [ ] AST builder - _internal AST walker that builds rich AST_
   - [ ] AST walker - _interface for traversing AST_
   - [ ] AST dumper- _utility walker to display AST structure_
   - [ ] Parser parity tests - _compatibility testing between old and new parsers_
2. [ ] Metadata - _this represents an `@Annotation`_
   - [x] Annotation and Property metadata - _information needed to construct annotation objects_ [#247]
   - [x] Property type and enum hiearchy [#256]
   - [ ] AST metadata collector (walker)
   - [ ] Scope - _holds information about subject (origin), active imports, ignored annotations and nesting level_
   - [ ] Reference resolver - _resolves unqualified annotation references based on given scope and strategy_
   - [ ] Property type parser - _parses `@var` to constraint value types_
3. [ ] Assembling
   - [ ] Annotation assembler - _builds actual annotation objects based on AST and metadata_
   - [ ] Acceptor - _determines whether visited annotation AST node should produce an annotation or be skipped (used to build internal/public or skip ignored annotations)_
   - [ ] Constraint validator - _validates annotation's property values against constraints (i.e. Required, Enum, `@var`)_
   - [ ] Constructor - _instantiates annotation objects based on chosen strategy (using a constructor or using property hydration)_

---

### Other problems to likely be resolved (but not guaranteed)

Generally [issues marked with 2.0 milestone](https://github.com/doctrine/annotations/milestone/4). Notably:
- Support for unqualified references in `@var` (#86)
- Supporting compound `@var` (#185 +  #129)
- FCQN with `::class` will not produce leading `\` (#141)
- Proper support for `use` in traits (#81)

---

_Any feedback is welcomed, either here or (preferably) on [Doctrine Slack](https://doctrine-project.org/slack) in `#annotations-ng-dev` channel._

**Comment by alcaeus** [comment]
> The namespace will be changed from `Doctrine\Common\Annotations` to `Doctrine\Annotations`

This was a hotly contested issue in the last attempt to create 2.0, so I'll just link previous discussion: https://github.com/doctrine/annotations/pull/75#discussion_r56872787.

> `FileCacheReader` - dropped in favor of doctrine/cache

If with "dropped in favour of" you mean "implemented generically for any doctrine/cache instance", then I can somewhat live with the change. We should also consider shipping readers that use a PSR-16 or PSR-6 cache given to them.

**Comment by stof** [comment]
>     * `FileCacheReader` - _dropped in favor of doctrine/cache_

this should read as `dropped in favor of CachedReader` instead, as the replacement is `CachedReader` (which already exists in 1.x)

**Comment by Majkl578** [comment]
@stof Thanks, updated.

**Comment by jaapio** [comment]
Why write your own docblock parser if the new phpdocumentor docblock parser is able to cover your back? Would be happy to assist with changes if needed

**Comment by stof** [comment]
@jaapio doctrine annotation are not the same than phpdoc. The phpdocumentor parser cannot replace the Doctrine annotation parser.

**Comment by jaapio** [comment]
With the new design of the package we left room for annotations. Don't know if it would make any sense for you guys.

**Comment by piotrooo** [comment]
What is a current state of this milestones?

**Comment by Majkl578** [comment]
@piotrooo I've cleaned up master (2.0-dev) where namespace has already been changed and most of the deprecated stuff has been dropped too. Now working on introducing new stuff to prepare for the parser replacement.
I also slightly updated the OP.

**Comment by piotrooo** [comment]
@Majkl578 have you any tasks to do? I can help with that release.
BTW. Thanks for good work.

**Comment by Majkl578** [comment]
After recent events I no longer intend to work on this. Sorry everyone.
